DRIVER_NAMES = {
    "ANT": ("Kimi Antonelli",    "ITA", "#e10600"),
    "RUS": ("George Russell",    "GBR", "#e10600"),
    "HAM": ("Lewis Hamilton",    "GBR", "#ff3333"),
    "LEC": ("Charles Leclerc",   "MON", "#ff3333"),
    "NOR": ("Lando Norris",      "GBR", "#cc0000"),
    "PIA": ("Oscar Piastri",     "AUS", "#cc0000"),
    "VER": ("Max Verstappen",    "NED", "#990000"),
    "HAD": ("Isack Hadjar",      "FRA", "#990000"),
    "LAW": ("Liam Lawson",       "NZL", "#b30000"),
    "LIN": ("Arvid Lindblad",    "GBR", "#b30000"),
    "GAS": ("Pierre Gasly",      "FRA", "#800000"),
    "COL": ("Franco Colapinto",  "ARG", "#800000"),
    "BEA": ("Oliver Bearman",    "GBR", "#666666"),
    "OCO": ("Esteban Ocon",      "FRA", "#666666"),
    "SAI": ("Carlos Sainz",      "ESP", "#ff6666"),
    "ALB": ("Alexander Albon",   "THA", "#ff6666"),
    "BOR": ("Gabriel Bortoleto", "BRA", "#e10600"),
    "HUL": ("N Nico Hulkenberg", "GER", "#e10600"),
    "BOT": ("Valtteri Bottas",   "FIN", "#aa0000"),
    "PER": ("Sergio Perez",      "MEX", "#aa0000"),
    "STR": ("Lance Stroll",      "CAN", "#770000"),
    "ALO": ("Fernando Alonso",   "ESP", "#770000"),
}

UPCOMING_RACES = [
    {"name": "Spanish Grand Prix",       "circuit": "Barcelona-Catalunya", "dt": "2026-06-14 13:00", "tz": "Europe/Madrid"},
    {"name": "Austrian Grand Prix",      "circuit": "Spielberg",           "dt": "2026-06-28 13:00", "tz": "Europe/Vienna"},
    {"name": "British Grand Prix",       "circuit": "Silverstone",         "dt": "2026-07-05 13:00", "tz": "Europe/London"},
    {"name": "Belgian Grand Prix",       "circuit": "Spa-Francorchamps",   "dt": "2026-07-19 13:00", "tz": "Europe/Brussels"},
    {"name": "Hungarian Grand Prix",     "circuit": "Budapest",            "dt": "2026-07-26 13:00", "tz": "Europe/Budapest"},
    {"name": "Dutch Grand Prix",         "circuit": "Zandvoort",           "dt": "2026-08-23 13:00", "tz": "Europe/Amsterdam"},
    {"name": "Italian Grand Prix",       "circuit": "Monza",               "dt": "2026-09-06 13:00", "tz": "Europe/Rome"},
    {"name": "Azerbaijan Grand Prix",    "circuit": "Baku",                "dt": "2026-09-26 12:00", "tz": "Asia/Baku"},
    {"name": "Singapore Grand Prix",     "circuit": "Marina Bay",          "dt": "2026-10-11 13:00", "tz": "Asia/Singapore"},
    {"name": "United States Grand Prix", "circuit": "Austin",              "dt": "2026-10-25 19:00", "tz": "America/Chicago"},
    {"name": "Mexico City Grand Prix",   "circuit": "Mexico City",         "dt": "2026-11-01 20:00", "tz": "America/Mexico_City"},
    {"name": "São Paulo Grand Prix",     "circuit": "São Paulo",           "dt": "2026-11-08 17:00", "tz": "America/Sao_Paulo"},
    {"name": "Las Vegas Grand Prix",     "circuit": "Las Vegas",           "dt": "2026-11-21 06:00", "tz": "America/Los_Angeles"},
    {"name": "Qatar Grand Prix",         "circuit": "Lusail",              "dt": "2026-11-29 17:00", "tz": "Asia/Qatar"},
    {"name": "Abu Dhabi Grand Prix",     "circuit": "Yas Island",          "dt": "2026-12-06 13:00", "tz": "Asia/Dubai"},
]
